# Generated by Django 4.0.4 on 2022-06-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraddress_options_alter_userprofile_options'),
        ('wishlist', '0002_remove_wishlist_created_at_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list_owner', to='users.userprofile'),
        ),
    ]
