# Generated by Django 4.0.4 on 2022-06-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('payed', 'payed'), ('shipped', 'shipped'), ('cancelled', 'cancelled')], default='new', max_length=20),
        ),
    ]
